name: build-single-arch

on:
  workflow_dispatch:

jobs:
  build-images:
    uses: k-candidate/gha-workflows/.github/workflows/docker-bake.yaml@bake
    with:
      bake_file: docker-bake-single.hcl
    secrets: inherit