name: Test Docker Bake 4

on:
  workflow_dispatch:

jobs:
  build-images:
    uses: k-candidate/gha-workflows/.github/workflows/docker-bake-5.yaml@bake
    secrets:
      dockerhub_username: ${{ secrets.MY_REGISTRY_USER }}
      dockerhub_token: ${{ secrets.MY_REGISTRY_TOKEN }}
    with:
      bake-file: ./testdir/testsubdir/docker-bake.hcl
