name: build-no-creds

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-images:
    uses: k-candidate/gha-workflows/.github/workflows/docker-bake.yaml@bake
    with:
      bake_file: ./docker-bake.hcl
      source: .
      export_mode: push
      registry: docker.io
    # NO secrets passed - uses builder repo defaults
