name: Test Call Reusable Workflow that has Env Secret

on:
  workflow_dispatch:

jobs:
  call-reusable:
    uses: k-candidate/gha-workflows/.github/workflows/test-reusable.yaml@main
    # NO secrets passed at all