name: Test Docker BAke 2

on:
  workflow_dispatch:

jobs:
  build-images:
    uses: k-candidate/gha-workflows/.github/workflows/docker-bake-2.yaml@bake
    secrets:
      REGISTRY_USERNAME: ${{ secrets.MY_REGISTRY_USER }}
      REGISTRY_PASSWORD: ${{ secrets.MY_REGISTRY_TOKEN }}
