name: Test Docker Bake 3

on:
  workflow_dispatch:

jobs:
  build-images:
    uses: k-candidate/gha-workflows/.github/workflows/docker-bake-3.yaml@bake
    secrets:
      REGISTRY_USERNAME: ${{ secrets.MY_REGISTRY_USER }}
      REGISTRY_PASSWORD: ${{ secrets.MY_REGISTRY_TOKEN }}
