name: Safely Encrypt Secret
on: workflow_dispatch

jobs:
  encrypt:
    runs-on: ubuntu-latest
    steps:
      - name: Install age
        run: sudo apt-get install age -y

      - name: Encrypt and Output
        env:
          MY_SECRET: ${{ secrets.TEST_CALLER_SECRET }}
          PUBLIC_KEY: "age1pmt766cp5gdxeapne6n3l29pravwgyl74ufuw3vfatzpk45tzdasgsr9ye"
        run: |
          # Encrypt the secret and convert to base64 for easy copying
          ENCRYPTED_VAL=$(echo -n "$MY_SECRET" | age -r "$PUBLIC_KEY" -a)
          
          echo "Copy the block below between the horizontal lines:"
          echo "-----------------------"
          echo "$ENCRYPTED_VAL"
          echo "-----------------------"