name: build-multi-target-single-arch

on:
  workflow_dispatch:

jobs:
  build-images:
    uses: k-candidate/gha-workflows/.github/workflows/docker-bake-8.yaml@bake
    with:
      bake-file: docker-bake-multi-target-single-arch.hcl
    secrets:
      dockerhub_username: ${{ secrets.MY_REGISTRY_USER }}
      dockerhub_token: ${{ secrets.MY_REGISTRY_TOKEN }}